[package]
name = "benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.12.1"
criterion = { version = "0.5", features = ["html_reports"] }
stunseed = { version = "0.1.0", path = "../stunseed" }

[[bench]]
name = "all"
harness = false
